  0%|          | 0/500 [00:00<?, ?it/s]/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/torch/autograd/graph.py:769: UserWarning: Error detected in SoftmaxBackward0. Traceback of forward call that caused the error:
zs_0
zp_0
zs_1
zp_1
recon_0_from_0
recon_1_from_0
recon_0_from_1
recon_1_from_1
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2270, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ender/Library/CloudStorage/OneDrive-HongKongBaptistUniversity/postdoc/SpaMV/main.py", line 104, in <module>
    model.train(min_epochs=100, max_epochs=args.epochs, min_kl=args.beta, max_kl=args.beta,
  File "/Users/ender/Library/CloudStorage/OneDrive-HongKongBaptistUniversity/postdoc/SpaMV/SpaMV/spamv.py", line 101, in train
    loss = self.get_elbo(epoch)
  File "/Users/ender/Library/CloudStorage/OneDrive-HongKongBaptistUniversity/postdoc/SpaMV/SpaMV/spamv.py", line 154, in get_elbo
    model_trace, guide_trace = get_importance_trace('flat', torch.inf, scale(self.model.model, 1 / self.n_obs),
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/pyro/infer/enum.py", line 65, in get_importance_trace
    model_trace = poutine.trace(
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/pyro/poutine/trace_messenger.py", line 216, in get_trace
    self(*args, **kwargs)
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/pyro/poutine/trace_messenger.py", line 191, in __call__
    ret = self.fn(*args, **kwargs)
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/Users/ender/Library/CloudStorage/OneDrive-HongKongBaptistUniversity/postdoc/SpaMV/SpaMV/model.py", line 156, in model
    x_tilde = getattr(self, "decoder_{}".format(j))(z)
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/ender/Library/CloudStorage/OneDrive-HongKongBaptistUniversity/postdoc/SpaMV/SpaMV/layers.py", line 44, in forward
    return F.softmax(self.fc2(hidden), dim=1)
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/torch/nn/functional.py", line 1888, in softmax
    ret = input.softmax(dim)
 (Triggered internally at /Users/runner/miniforge3/conda-bld/libtorch_1729084846508/work/torch/csrc/autograd/python_anomaly_mode.cpp:116.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  0%|          | 0/500 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ender/Library/CloudStorage/OneDrive-HongKongBaptistUniversity/postdoc/SpaMV/main.py", line 104, in <module>
    model.train(min_epochs=100, max_epochs=args.epochs, min_kl=args.beta, max_kl=args.beta,
  File "/Users/ender/Library/CloudStorage/OneDrive-HongKongBaptistUniversity/postdoc/SpaMV/SpaMV/spamv.py", line 102, in train
    loss.backward()
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/opt/anaconda3/envs/scTM/lib/python3.12/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [3482, 3000]], which is output 0 of SoftmaxBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
